# ULAB Physics & Astronomy: Python Module VII

In [ ]:
#make sure to run this cell
# %load_ext autoreload
# %autoreload 2
import tests

## Question 1: the basics

First, import ``numpy`` as the namespace ``np``. 

In [ ]:
...

Now, create a 1D array of integers ``arr`` from  1 to 11 **using ``numpy.linspace``**.

In [ ]:
arr = ...

Finally, create a new array ``final_array`` that contains only the odd values of ``arr``. **You must use a single line of code and you should not use a list comprehension.** Hint: boolean-valued indexing.

In [ ]:
final_array = ...

In [ ]:
tests.run('test_1', arr, final_array)

## Question 2: Stacking arrays 

You are given two 2D arrays ``a`` and ``b``. For example,

```
>>> a
array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])
       
>>> b
array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])
```

### 2a
Implement a function ``vstacked`` which returns a new array with the values of ``a`` and ``b`` vertically stacked. For example,

```
>>> vstacked(a,b)
array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])
```

Hint: you can use ``numpy.vstack`` or ``numpy.concatenate`` and specify axis.

In [ ]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

def vstacked(a,b):
    ...

In [ ]:
print(vstacked(a,b))
tests.run('test_2a', vert_array)

### 2b

Implement a function ``hstacked`` which returns parameters ``a`` and ``b`` horizontally stacked. For example,

```
>>> hstacked(a,b)
array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])
```

In [ ]:
def hstacked(a,b):
    ...

In [ ]:
tests.run('test_2b', hstacked)

## Question 3
### 3a
Implement a function ``dmax`` that returns double the larger of the two values ``x`` or ``y``.

In [ ]:
def dmax(x, y):
    ...

In [ ]:
tests.run('test_3a', dmax)

### 3b

Suppose we have two arrays,
```
>>> a
array([1, 2, 3])
>>> b
array([2, 2, 2])
```
and we want to apply the function ``dmax`` to ``a`` and ``b``,
```
>>> maxed
array([4, 4, 6])
```

We could use a for loop,
```
maxed = []
for i in range(3):
    maxed.append(dmax(a[i], b[i]))
```
However, this is very slow because python has a lot of overhead! Instead, we can use numpy to vectorize the function. A vectorized function takes a sequence of ndarrays and evaluates the python function over each index of the arrays. For example,
```
>>> dmax_vec = ... # your job!
>>> maxed = dmax_vec(a,b)
>>> maxed
array([4., 4., 6.])
```
Not only is this cleaner to read, but it runs much faster because numpy is implemented in C!

Define ``dmax_vec``. Hint: use ``numpy.vectorize`` and specify an appropriate ``otypes``.

In [ ]:
dmax_vec = ...

In [ ]:
tests.run('test_3b', dmax_vec)

## Question 4 : Converting to Grayscale

Here we have an image of the sunset over the Bay [taken UC Berkeley 2018]

In [ ]:
import matplotlib.pyplot as plt
from matplotlib import image

img = image.imread('bay.jpeg')
plt.imshow(img)
plt.show()

``img`` is a numpy array with shape,
```
>>> img.shape
(1280, 1280, 3)
```

This indicates that the images is 1280x1280 pixels large with 3 color channels (R, G, B). The data is stored as a 1280 row by 1280 column matrix where each element of the matrix is an array containing the color values of each pixel.

Suppose we believe this image would look better in grayscale. To convert a colored image to grayscale, we must create a new array of size ``(1280, 1280)`` and combine the 3 color values into a single grayscale value.

Using eq. 7 of this [reference](grayscale_conversion.pdf), create a new image ``grey`` that is the grayscale version of ``img``.

In [ ]:
grey = ...

In [ ]:
plt.imshow(grey, cmap='gray')
plt.show()
tests.run('test_4', grey)

## Submission

Check to make sure that you have answered all questions. Run all the cells so that all output is visible. Finally, export this notebook as a PDF (File/Download As/PDF via LaTeX (.pdf)) and submit to bCourses.

<b>References:</b> 

Questions inspired by work by Selva Prabhakaran and Vasu Gupta. 

Images: Yi Zhu, 2018

Last Updated: Jan 2022